-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 12:43:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema climatologia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema climatologia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `climatologia` DEFAULT CHARACTER SET utf8 ;
USE `climatologia` ;

-- -----------------------------------------------------
-- Table `climatologia`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climatologia`.`zona` (
  `idzona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idzona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climatologia`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climatologia`.`ubicacion` (
  `idubicacion` INT NOT NULL,
  `idzona` INT NOT NULL,
  `alcaldia` VARCHAR(45) NULL,
  `area_totalm2` FLOAT NULL,
  `espacio_publico_m2hab` FLOAT NULL,
  `densidad_de_poblacion` FLOAT NULL,
  PRIMARY KEY (`idubicacion`),
  INDEX `fk_ubicacion_zona1_idx` (`idzona` ASC) VISIBLE,
  CONSTRAINT `fk_ubicacion_zona1`
    FOREIGN KEY (`idzona`)
    REFERENCES `climatologia`.`zona` (`idzona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climatologia`.`mes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climatologia`.`mes` (
  `idmes` INT NOT NULL,
  `mes` VARCHAR(45) NULL,
  PRIMARY KEY (`idmes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climatologia`.`precipitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climatologia`.`precipitacion` (
  `idprecipitacion` INT NOT NULL,
  `idmes` INT NOT NULL,
  `porcentaje` FLOAT NULL,
  `promedio` FLOAT NULL,
  PRIMARY KEY (`idprecipitacion`),
  INDEX `fk_precipitacion_mes1_idx` (`idmes` ASC) VISIBLE,
  CONSTRAINT `fk_precipitacion_mes1`
    FOREIGN KEY (`idmes`)
    REFERENCES `climatologia`.`mes` (`idmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climatologia`.`evapotranspiracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climatologia`.`evapotranspiracion` (
  `idevapotranspiracion` INT NOT NULL,
  `idmes` INT NOT NULL,
  `idprecipitacion` INT NOT NULL,
  `nivel_de_evapotranspiracion` DOUBLE NULL,
  `balance_hidrico` DOUBLE NULL,
  PRIMARY KEY (`idevapotranspiracion`),
  INDEX `fk_evapotranspiracion_mes1_idx` (`idmes` ASC) VISIBLE,
  INDEX `fk_evapotranspiracion_precipitacion1_idx` (`idprecipitacion` ASC) VISIBLE,
  CONSTRAINT `fk_evapotranspiracion_mes1`
    FOREIGN KEY (`idmes`)
    REFERENCES `climatologia`.`mes` (`idmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evapotranspiracion_precipitacion1`
    FOREIGN KEY (`idprecipitacion`)
    REFERENCES `climatologia`.`precipitacion` (`idprecipitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climatologia`.`calidad_aire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climatologia`.`calidad_aire` (
  `idcalidad_aire` INT NOT NULL,
  `idzona` INT NOT NULL,
  `idmes` INT NOT NULL,
  `calidad` VARCHAR(45) NULL,
  `porcentaje` INT NULL,
  `ppm` FLOAT NULL,
  PRIMARY KEY (`idcalidad_aire`),
  INDEX `fk_calidad_viento_zona1_idx` (`idzona` ASC) VISIBLE,
  INDEX `fk_calidad_aire_mes1_idx` (`idmes` ASC) VISIBLE,
  CONSTRAINT `fk_calidad_viento_zona1`
    FOREIGN KEY (`idzona`)
    REFERENCES `climatologia`.`zona` (`idzona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calidad_aire_mes1`
    FOREIGN KEY (`idmes`)
    REFERENCES `climatologia`.`mes` (`idmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climatologia`.`intensidad_calorifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climatologia`.`intensidad_calorifica` (
  `idintensidad` INT NOT NULL,
  `idubicacion` INT NOT NULL,
  `intensidad` VARCHAR(45) NULL,
  `rango_temperatura` VARCHAR(45) NULL,
  PRIMARY KEY (`idintensidad`),
  INDEX `fk_intensidad_calorifica_ubicacion1_idx` (`idubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_intensidad_calorifica_ubicacion1`
    FOREIGN KEY (`idubicacion`)
    REFERENCES `climatologia`.`ubicacion` (`idubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climatologia`.`humedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climatologia`.`humedad` (
  `idhumedad` INT NOT NULL,
  `idmes` INT NOT NULL,
  `porcentaje` FLOAT NULL,
  PRIMARY KEY (`idhumedad`),
  INDEX `fk_humedad_mes1_idx` (`idmes` ASC) VISIBLE,
  CONSTRAINT `fk_humedad_mes1`
    FOREIGN KEY (`idmes`)
    REFERENCES `climatologia`.`mes` (`idmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
